# Generated by Django 5.1.15 on 2026-10-01 14:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("links", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyLinkStats",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(db_index=True)),
                ("total_clicks", models.BigIntegerField(default=0)),
                ("unique_visitors", models.BigIntegerField(default=0)),
                ("bot_clicks", models.BigIntegerField(default=0)),
                ("mobile_clicks", models.BigIntegerField(default=0)),
                ("desktop_clicks", models.BigIntegerField(default=0)),
                ("tablet_clicks", models.BigIntegerField(default=0)),
                (
                    "top_country",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "top_referrer",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "short_link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_stats",
                        to="links.shortlink",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["short_link", "date"],
                        name="analytics_d_short_l_87e2ee_idx",
                    )
                ],
                "unique_together": {("short_link", "date")},
            },
        ),
    ]
