# Generated by Django 5.1.15 on 2026-10-01 14:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("links", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClickEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "visitor_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("ip_hash", models.CharField(blank=True, max_length=64)),
                (
                    "country",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                ("region", models.CharField(blank=True, max_length=100, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                (
                    "device_type",
                    models.CharField(db_index=True, default="unknown", max_length=32),
                ),
                (
                    "browser",
                    models.CharField(db_index=True, default="unknown", max_length=64),
                ),
                (
                    "browser_version",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "os",
                    models.CharField(db_index=True, default="unknown", max_length=64),
                ),
                ("os_version", models.CharField(blank=True, default="", max_length=32)),
                ("user_agent", models.TextField(blank=True, default="")),
                ("referrer", models.TextField(blank=True, default="")),
                (
                    "referrer_domain",
                    models.CharField(db_index=True, default="direct", max_length=255),
                ),
                (
                    "utm_source",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                (
                    "utm_medium",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "utm_campaign",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                ("utm_term", models.CharField(blank=True, default="", max_length=255)),
                (
                    "utm_content",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("is_bot", models.BooleanField(db_index=True, default=False)),
                ("bot_name", models.CharField(blank=True, default="", max_length=100)),
                ("language", models.CharField(blank=True, default="", max_length=32)),
                ("timezone", models.CharField(blank=True, default="", max_length=64)),
                ("response_status", models.IntegerField(default=302)),
                (
                    "short_link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="click_events",
                        to="links.shortlink",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["short_link", "timestamp"],
                        name="tracking_cl_short_l_71ec96_idx",
                    ),
                    models.Index(
                        fields=["visitor_id", "timestamp"],
                        name="tracking_cl_visitor_6ba3f4_idx",
                    ),
                    models.Index(
                        fields=["country", "timestamp"],
                        name="tracking_cl_country_98515d_idx",
                    ),
                ],
            },
        ),
    ]
