# Generated by Django 5.1.15 on 2026-10-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clickevent",
            name="event_id",
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
